openapi: 3.0.0
info:
  title: Devices
  version: '1.0'
  description: |-
    Interact with the devices service to get a list of registered devices, add or remove devices and updating existing records.

    Use this API to leverage CloudHome's central repository of devices that will then allow users to manage home automation systems.
  contact:
    name: Stephen Price
    url: 'https://www.linkedin.com/in/slprice/'
    email: stephen@stoplight.io
  termsOfService: cloudhome.io/api/devices/terms
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: 'https://cloudhome.io'
    description: CloudHome device platform
paths:
  '/api/devices/{accountid}/{locationid}':
    get:
      summary: getDevices
      tags:
        - devices
        - IOT
      responses: {}
      operationId: get-api-devices
      description: Returns a list of devices
    post:
      summary: newDevice
      tags:
        - devices
        - IOT
      responses: {}
      operationId: post-api-devices
    put:
      summary: updateDevice
      tags:
        - devices
        - IOT
      responses: {}
      operationId: put-api-devices
    delete:
      summary: removeDevice
      tags:
        - devices
        - IOT
      responses: {}
      operationId: delete-api-devices
    parameters:
      - schema:
          type: string
        name: accountid
        in: path
        required: true
        description: unique per account (see 'My Account' for more information)
      - schema:
          type: string
        name: locationid
        in: path
        required: true
        description: location associated with the devices (see 'My Locations' for more)
components:
  schemas: {}
  securitySchemes:
    API Key:
      name: API Key
      type: apiKey
      in: query
      description: Provided upon account registration (see 'My Account' for more information)
